name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
           # Options
          user: jzaleta
          template: classic
          base: header, activity, community, repositories
          base_indepth: yes
          repositories: 1000
          repositories_affiliations: owner, collaborator
          config_timezone: America/Mexico_City
          config_order: base.header, base.activity+community, base.repositories, languages, notable, habits, achivements

          plugin_notable: yes
          
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 500

          plugin_languages: yes
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          
          plugin_achievements: yes
